# Generated by Django 5.1.5 on 2025-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_registereduserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduserinfo',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
